title: Noah E. Wolfe
position: Ph.D. Student
affiliation: Massachusetts Institute of Technology
email: newolfe@mit.edu
keywords: astrophysics, gravitational waves
google_scholar: https://scholar.google.com/citations?user=E4uiqucAAAAJ
github_link: https://github.com/noahewolfe
linkedin: https://www.linkedin.com/in/noah-wolfe-731845188/
avatar: ./assets/img/noah.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
